build.gradle, src/main/java/com/cherrypick/backend/domain/user/controller/UserController.java, src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java, src/main/java/com/cherrypick/backend/global/config/SwaggerConfig.java, src/main/java/com/cherrypick/backend/global/config/oauth/FilterChainExceptionHandler.java, src/main/java/com/cherrypick/backend/global/config/oauth/JWTFilter.java, src/main/java/com/cherrypick/backend/global/config/oauth/OAuth2Service.java, src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java, src/main/java/com/cherrypick/backend/global/util/JWTUtil.java
- 스웨거 붙였습니다.
- 스웨거에서 JWT 를 사용하기 위한 TEST API를 만들었습니다.
- 스프링 시큐리티에서 인증 실패시 /login으로 리다이렉트 되던 것을 401오류를 반환하도록 바꾸었습니다.
- FilterChainExceptionHandler : 인증 실패 시 401 에러를 반환합니다.
어떤 변경 사항이 있나요?
=> RP-34 스웨거 적용

src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealCreateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java, src/main/java/com/cherrypick/backend/domain/vote/dto/request/VoteRequestDTO.java, src/main/java/com/cherrypick/backend/domain/vote/dto/response/VoteResponseDTO.java, src/main/java/com/cherrypick/backend/domain/vote/entity/Vote.java, src/main/java/com/cherrypick/backend/domain/vote/enums/DislikeReason.java, src/main/java/com/cherrypick/backend/domain/vote/enums/VoteType.java, src/main/java/com/cherrypick/backend/domain/vote/repository/VoteRepository.java, src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java, src/main/java/com/cherrypick/backend/global/exception/enums/VoteErrorCode.java
- 게시글 투표 기능 구현
- 추천, 비추천, 투표 취소 가능
- 비추천 시 사유 필수 
어떤 변경 사항이 있나요?
- 비추천 사유 ENUM은 추후 결정되면 변경
- 추천 TRUE, 비추천 FALSE인데.. LIKE와 DISLIKE가 낫나용?
=> RP-18 핫딜 게시글 투표 기능 구현

src/main/java/com/cherrypick/backend/domain/category/repository/CategoryRepository.java, src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java, src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealSearchRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealSearchResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/repository/DealRepository.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/deal/vo/Filter.java, src/main/java/com/cherrypick/backend/domain/deal/vo/PriceFilter.java, src/main/java/com/cherrypick/backend/global/exception/enums/DealErrorCode.java
- 핫딜 검색 기능 구현했습니다
- 기본적으로 품절 상품과 다양한 가격 상품은 보이지 않습니다.
- 아무런 필터를 넣지 않으면 전체조회입니다.
- 카테고리가 상세 조회에서 ID로 출력되던 문제 수정했습니다.
어떤 변경 사항이 있나요?
- 정렬기준은 저가순, 고가순을 제외하고는 서비스 로직으로 처리했습니다.
- 정렬기준 중 랭킹순은 아직 개발하지 않았습니다. 
- 그 외엔 JPQL으로 처리했습니다.
=> RP-17 핫딜 검색 기능 구현

build.gradle, src/main/java/com/cherrypick/backend/CherrypickBackendApplication.java, src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealCreateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealUpdateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/image/controller/ImageController.java, src/main/java/com/cherrypick/backend/domain/image/dto/request/ImageUploadRequestDTO.java, src/main/java/com/cherrypick/backend/domain/image/dto/response/ImageDeleteResponseDTO.java, src/main/java/com/cherrypick/backend/domain/image/dto/response/ImageUploadResponseDTO.java, src/main/java/com/cherrypick/backend/domain/image/entity/Image.java, src/main/java/com/cherrypick/backend/domain/image/repository/ImageRepository.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java, src/main/java/com/cherrypick/backend/domain/image/vo/ImageUrl.java, src/main/java/com/cherrypick/backend/global/exception/enums/ImageErrorCode.java, src/main/java/com/cherrypick/backend/global/s3/S3Config.java, src/main/java/com/cherrypick/backend/global/s3/S3Uploader.java, src/main/resources/application.yml
=> RP-10 게시판 로직 중간 머지

.github/workflows/deploy.yml, dockerfile
- 깃허브 액션 CI/CD 구축
- ENV는 깃허브 시크릿으로 관리
어떤 변경 사항이 있나요?
=> [RP-9] CI/CD 구축

src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java, src/main/java/com/cherrypick/backend/domain/image/controller/ImageController.java, src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java
=> RP-10 핫딜, 이미지, 투표 기능 스웨거 구현

src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/image/repository/ImageRepository.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java, src/main/java/com/cherrypick/backend/domain/oauth/controller/AuthController.java, src/main/java/com/cherrypick/backend/domain/user/controller/UserController.java, src/main/java/com/cherrypick/backend/domain/user/dto/AuthenticationDetailDTO.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserRequestDTOs.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserResponseDTOs.java, src/main/java/com/cherrypick/backend/domain/user/repository/UserRepository.java, src/main/java/com/cherrypick/backend/domain/user/service/UserService.java, src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java, src/main/java/com/cherrypick/backend/global/config/security/JWTFilter.java, src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java, src/main/java/com/cherrypick/backend/global/util/AuthUtil.java, src/main/java/com/cherrypick/backend/global/util/JWTUtil.java, src/main/resources/application.yml
유저 정보 수정 / 유저 조회 기능이 추가되었습니다.
로그인 된 유저에 대한 정보를 불러오는 것이고, 타 유저에 대한 조회는 추후 구현 예정입니다.
어떤 변경 사항이 있나요?
=> RP-32 유저 정보 / 유저 조회

src/main/java/com/cherrypick/backend/domain/comment/controller/CommentController.java, src/main/java/com/cherrypick/backend/domain/comment/dto/request/CommentRequestDTOs.java, src/main/java/com/cherrypick/backend/domain/comment/dto/response/BestCommentResponseDTO.java, src/main/java/com/cherrypick/backend/domain/comment/dto/response/CommentListResponseDTO.java, src/main/java/com/cherrypick/backend/domain/comment/dto/response/CommentResponseDTOs.java, src/main/java/com/cherrypick/backend/domain/comment/entity/Comment.java, src/main/java/com/cherrypick/backend/domain/comment/repository/CommentLikeRepository.java, src/main/java/com/cherrypick/backend/domain/comment/repository/CommentRepository.java, src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java, src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/image/controller/ImageController.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java, src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java, src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java, src/main/java/com/cherrypick/backend/global/exception/enums/CommentErrorCode.java
- 댓글 생성, 삭제, 베스트 댓글 조회, 댓글 전체 조회 API 구현했습니다
- 유저 이미지 조회 붙였습니다
어떤 변경 사항이 있나요?
- 풀 받고 진행해서 내용이 좀 긴데, 제 것만 봐주시면 됩니당
=> RP-14 댓글 기능 구현

src/main/java/com/cherrypick/backend/domain/comment/repository/CommentRepository.java, src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java, src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealSearchPageResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/repository/DealRepository.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/image/controller/ImageController.java, src/main/java/com/cherrypick/backend/domain/image/repository/ImageRepository.java, src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java, src/main/java/com/cherrypick/backend/domain/vote/enums/DislikeReason.java, src/main/java/com/cherrypick/backend/domain/vote/repository/VoteRepository.java
- 전체 검색 무한 스크롤 페이징 처리
- 쿼리 N+1 문제 해결
- 비추천 사유 수정
어떤 변경 사항이 있나요?
=> RP-10 핫딜 전체 조회(검색) 페이징 처리 및 N+1 문제 해결

src/main/java/com/cherrypick/backend/domain/comment/controller/CommentController.java, src/main/java/com/cherrypick/backend/domain/comment/repository/CommentLikeRepository.java, src/main/java/com/cherrypick/backend/domain/comment/repository/CommentRepository.java, src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/image/controller/ImageController.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java, src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java, src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java, src/main/java/com/cherrypick/backend/global/exception/enums/CommentErrorCode.java
=> RP-9 핫딜 검색 수정사항 배포

src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealCrawlService.java, src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java, src/main/java/com/cherrypick/backend/domain/hashtag/entity/DealTag.java, src/main/java/com/cherrypick/backend/domain/hashtag/entity/HashTag.java, src/main/java/com/cherrypick/backend/domain/hashtag/repository/DealTagRepository.java, src/main/java/com/cherrypick/backend/domain/hashtag/repository/HashTagRepository.java, src/main/java/com/cherrypick/backend/domain/hashtag/service/HashTagService.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java, src/main/java/com/cherrypick/backend/domain/oauth/controller/AuthController.java, src/main/java/com/cherrypick/backend/domain/oauth/dto/OAuth2UserDTO.java, src/main/java/com/cherrypick/backend/domain/user/controller/UserController.java, src/main/java/com/cherrypick/backend/domain/user/dto/AuthenticationDetailDTO.java, src/main/java/com/cherrypick/backend/domain/user/entity/User.java, src/main/java/com/cherrypick/backend/domain/user/enums/Role.java, src/main/java/com/cherrypick/backend/domain/user/enums/UserStatus.java, src/main/java/com/cherrypick/backend/global/config/security/OAuth2SuccessHandler.java, src/main/java/com/cherrypick/backend/global/util/JWTUtil.java
파일 구조 조금 바뀌었습니당
어떤 변경 사항이 있나요?
=> RP-62 전반적인 리펙토링

src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealSearchRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/repository/DealRepository.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/deal/vo/PriceFilter.java
=> RP-10 리픽 랭킹순 구현

src/main/java/com/cherrypick/backend/domain/category/controller/CategoryController.java, src/main/java/com/cherrypick/backend/domain/category/dto/response/CategoryListDTO.java, src/main/java/com/cherrypick/backend/domain/category/entity/Category.java, src/main/java/com/cherrypick/backend/domain/category/service/CategoryService.java, src/main/java/com/cherrypick/backend/domain/deal/controller/RecommenderController.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealCrawlService.java, src/main/java/com/cherrypick/backend/domain/discount/cotroller/DiscountController.java, src/main/java/com/cherrypick/backend/domain/discount/dto/DiscountResponseListDTO.java, src/main/java/com/cherrypick/backend/domain/discount/service/DiscountService.java, src/main/java/com/cherrypick/backend/domain/store/controller/StoreController.java, src/main/java/com/cherrypick/backend/domain/store/dto/StoreResponseListDTO.java, src/main/java/com/cherrypick/backend/domain/store/service/StoreService.java, src/main/java/com/cherrypick/backend/domain/user/controller/UserController.java
카테고리 / 할인 / 스토어 정보 조회
각 데이터는 파이썬을 통해 DB에 업로드 (csv 파일)
업로더는 노션 DOCS 정책 및 데이터에 올려뒀음.
어떤 변경 사항이 있나요?
현재는 호출마다 연산 후 API를 반환. 카테고리는 메인페이지에서 호출하기 때문에 자주 호출됨.
하지만 이는 매우 비효율적인 API로, 이후 리펙터링 때에는 캐싱을 고려해야함.
=> RP-30 카테고리/할인/스토어 정보 조회

src/main/java/com/cherrypick/backend/domain/category/dto/response/CategoryListDTO.java, src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java, src/main/java/com/cherrypick/backend/domain/deal/controller/RecommenderController.java, src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealRequestDTOs.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java, src/main/java/com/cherrypick/backend/domain/image/repository/ImageRepository.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java, src/main/java/com/cherrypick/backend/domain/oauth/controller/AuthController.java, src/main/java/com/cherrypick/backend/domain/oauth/service/AuthService.java, src/main/java/com/cherrypick/backend/domain/user/controller/UserController.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserRequestDTOs.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserResponseDTOs.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserUpdateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/user/entity/User.java, src/main/java/com/cherrypick/backend/domain/user/enums/Gender.java, src/main/java/com/cherrypick/backend/domain/user/repository/UserRepository.java, src/main/java/com/cherrypick/backend/domain/user/service/UserService.java, src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java, src/main/resources/application.yml
- 유저 조회/수정 API의 필드가 바뀌었습니다.
- 소프트 딜리트를 구현하였습니다.
어떤 변경 사항이 있나요?
=> RP-32 유저 삭제 구현 / API 수정

src/main/java/com/cherrypick/backend/global/s3/S3Uploader.java
=> Fix S3 이미지 퍼블릭 URL 접근 되도록 수정

src/main/java/com/cherrypick/backend/global/s3/S3Uploader.java
=> Fix: S3 이미지 퍼블릭 URL 접근 되도록 수정

src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealSearchResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java, src/main/java/com/cherrypick/backend/domain/user/entity/User.java, src/main/java/com/cherrypick/backend/domain/vote/entity/Vote.java, src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java
- 딜스코어 계산 및 반환
- DB에는 double 타입으로 저장, response 때는 소숫점 버리고 int 타입으로 반환
- 저항 가중치로 인해 투표 후 취소했을 때 이전에 반영됐던 점수 계산이 쉽지 않은 상황 발생
- 따라서 Vote 엔터티에 유저가 영향을 끼친 점수를 저장(score) 후 투표 수정 시 score를 빼고 새로 계산하여 넣는 방식으로 구현함
어떤 변경 사항이 있나요?
=> Feature 딜스코어 구현

src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealSearchResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java, src/main/java/com/cherrypick/backend/domain/user/entity/User.java, src/main/java/com/cherrypick/backend/domain/vote/entity/Vote.java, src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java
=> heat 및 정렬 에러 해결 배포

src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealCreateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
- 최저가 구매 방법을 설명하는 discountDescription 추가
- 추후 디자인 나오면 reponse하는 부분도 구현해야 함
어떤 변경 사항이 있나요?
=> Feat: 핫딜 할인방법 설명 컬럼 추가

src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealCreateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
=> Fix DiscountDescription 상세조회에서 response

src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
=> Feat: DiscountDescription 상세조회에서 response

build.gradle, src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealSearchRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealSearchResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java
=> Fix: 핫딜 전체조회에서 유저 닉네임 반환하도록 수정

src/main/java/com/cherrypick/backend/domain/comment/controller/CommentController.java, src/main/java/com/cherrypick/backend/domain/comment/entity/Comment.java, src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java, src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealCrawlService.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/hashtag/service/HashTagService.java, src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java, src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java, src/main/resources/application.yml
유저 행동로그가 연결되고 글을 생성할때 해시태그가 연결됩니다.
어떤 변경 사항이 있나요?
=>  #84 해시태그 생성 및 유저 행동로그 연결

src/main/java/com/cherrypick/backend/domain/deal/repository/DealRepository.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/resources/application.yml
=> Fix: 핫딜 전체조회에서 hasNext가 false로 나오는 문제 해결

src/main/java/com/cherrypick/backend/domain/oauth/controller/AuthController.java, src/main/java/com/cherrypick/backend/domain/oauth/dto/AuthRequestDTOs.java, src/main/java/com/cherrypick/backend/domain/oauth/dto/AuthResponseDTOs.java, src/main/java/com/cherrypick/backend/domain/oauth/dto/OAuth2UserDTO.java, src/main/java/com/cherrypick/backend/domain/oauth/dto/RegisterDTO.java, src/main/java/com/cherrypick/backend/domain/oauth/dto/UserEnvDTO.java, src/main/java/com/cherrypick/backend/domain/oauth/service/AuthService.java, src/main/java/com/cherrypick/backend/domain/user/dto/UserUpdateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/user/entity/User.java, src/main/java/com/cherrypick/backend/domain/user/enums/Role.java, src/main/java/com/cherrypick/backend/domain/user/enums/UserStatus.java, src/main/java/com/cherrypick/backend/domain/user/service/UserService.java, src/main/java/com/cherrypick/backend/global/config/security/CustomAuthorizationRequestResolver.java, src/main/java/com/cherrypick/backend/global/config/security/OAuth2SuccessHandler.java, src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java, src/main/java/com/cherrypick/backend/global/util/AuthUtil.java, src/main/java/com/cherrypick/backend/global/util/JWTUtil.java, src/main/resources/application.yml
- 신규 유저가 로그인 시 바로 로그인되는 것이 아닌, 등록 토큰을 발급 받고 해당 토큰을 통해 등록합니다.
- 주석이 추가되었습니다.
어떤 변경 사항이 있나요?
인증 완료 시 EC2 서버로 데이터가 넘어가는 OAuth2.0 특성상, 배포 후 에러가 나는지 검증해야합니다.
=> RP-86 신규 유저 로그인 분기

src/main/java/com/cherrypick/backend/domain/comment/entity/Comment.java, src/main/java/com/cherrypick/backend/domain/comment/entity/CommentLike.java, src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java, src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/hashtag/entity/DealTag.java, src/main/java/com/cherrypick/backend/domain/oauth/controller/AuthController.java, src/main/java/com/cherrypick/backend/domain/oauth/dto/OAuth2UserDTO.java, src/main/java/com/cherrypick/backend/domain/oauth/service/AuthService.java, src/main/java/com/cherrypick/backend/domain/user/entity/User.java, src/main/java/com/cherrypick/backend/domain/vote/entity/Vote.java, src/main/java/com/cherrypick/backend/global/config/SwaggerConfig.java, src/main/java/com/cherrypick/backend/global/config/security/OAuth2SuccessHandler.java, src/main/java/com/cherrypick/backend/global/exception/enums/GlobalErrorCode.java, src/main/java/com/cherrypick/backend/global/util/JWTUtil.java
-  cascade가 변경되었습니다.
- 이제 토큰 획득 시에 이메일을 함께 받습니다.
- 리프레시 토큰이 정상 작동합니다.
어떤 변경 사항이 있나요?
=> RP-86 인증 프로세스 리펙터링

src/main/java/com/cherrypick/backend/domain/comment/controller/CommentController.java, src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java, src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java, src/main/java/com/cherrypick/backend/domain/oauth/controller/AuthController.java, src/main/java/com/cherrypick/backend/domain/test/TestController.java, src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java, src/main/java/com/cherrypick/backend/global/config/SwaggerConfig.java, src/main/java/com/cherrypick/backend/global/config/security/OAuth2SuccessHandler.java, src/main/resources/application.yml
- HTTP로 접근 시 HTTPS로 리디렉션
- local, dev 환경에서만 스웨거 활성화 되도록 수정
- local, dev 환경에서만 테스트 API 들이 활성화되도록 수정
- 스프링 필터체인 활성화
- CORS 활성화
- JWT 토큰 키 및 유효기간 ENV 파일로 이관
어떤 변경 사항이 있나요?
- YML / ENV 파일 변경
=> RP-100 배포 전 보안 및 잔 작업

src/main/java/com/cherrypick/backend/domain/comment/dto/request/CommentRequestDTOs.java, src/main/java/com/cherrypick/backend/domain/comment/dto/response/BestCommentResponseDTO.java, src/main/java/com/cherrypick/backend/domain/comment/dto/response/CommentListResponseDTO.java, src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java, src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
=> Relese 핫딜 조회수 DB 관리 및 댓글 좋아요 여부 반환 기능 배포

build.gradle, src/main/java/com/cherrypick/backend/CherrypickBackendApplication.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealCrawlService.java, src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java, src/main/java/com/cherrypick/backend/domain/oauth/service/AuthService.java, src/main/java/com/cherrypick/backend/domain/test/TestController.java, src/main/java/com/cherrypick/backend/domain/user/service/UserService.java, src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java, src/main/java/com/cherrypick/backend/global/config/security/CustomAuthorizationRequestResolver.java, src/main/java/com/cherrypick/backend/global/config/security/FilterChainExceptionHandler.java, src/main/java/com/cherrypick/backend/global/config/security/RequestLogFilter.java, src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java, src/main/java/com/cherrypick/backend/global/exception/handler/GlobalExceptionHandler.java, src/main/java/com/cherrypick/backend/global/util/LogService.java, src/main/resources/application.yml, src/main/resources/logback-spring.xml
- logstash 연결
- API 호출 로그 구현
- 에러 로그 구현
- 서버 시작 로그 구현
- 스프링 시큐리티 소수 변경
어떤 변경 사항이 있나요?
=> RP-101 ELK 적용

src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
=> Fix: 핫딜 상세조회에서 유저의 voteType response

src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealUpdateRequestDTO.java, src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
=> 핫딜 상세조회에서 discountName String으로 반환 및 핫딜 수정에서 discountDescription 누락 해결

src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java
=> Feat 이미지 삭제 API 권한 인증 로직 추가

build.gradle, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/image/dto/request/ImageUploadRequestDTO.java, src/main/java/com/cherrypick/backend/domain/image/service/ImageService.java, src/main/java/com/cherrypick/backend/domain/linkprice/controller/LinkPriceController.java, src/main/java/com/cherrypick/backend/domain/linkprice/service/LinkPriceService.java, src/main/java/com/cherrypick/backend/global/exception/enums/LinkPriceErrorCode.java, src/main/resources/application.yml
- 핫딜 생성 시 오리지날 url이 자동으로 딥링크로 변환되어 DB에 저장됨
- OPENAI 에러 이슈로 핫딜 생성이 안되어 딥링크 변환 테스트 API 구현하여 로직 작동 확인함
- 이미지 업로드 API 수정사항 반영 (이제 Index request 안 받음)
- 그 외 S3 이미지 폴더명 리팩토링, 어필리에이트 환경변수 추가됨
어떤 변경 사항이 있나요?
=> RP-115 링크프라이스 딥링크 변환 구현

src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java, src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java, src/main/java/com/cherrypick/backend/domain/linkprice/controller/LinkPriceController.java, src/main/java/com/cherrypick/backend/domain/linkprice/service/LinkPriceService.java, src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java, src/main/java/com/cherrypick/backend/global/exception/enums/LinkPriceErrorCode.java
- URL 검증 로직
- 딥링크 생성 에러 문구 수정
- 딥링크 생성 에러 수정
- 리다이렉션 API 구현
어떤 변경 사항이 있나요?
=> RP-118 핫딜 생성 및 딥링크 관련 개선
